### PR TITLE
cmd/herserver: remove validator immediately when disconnect

### PR DESCRIPTION
**Pull request by cuonglm**
Removing validator when disconnect is done synchronously after a block
time. We want to it to be removed immediately when disconnection occurs,
so moving the check in separated goroutine. It is actually have a 1
second delay, it is good enough, we can increase or remove it later if
it affects.

While at it, also refactoring the code.

## Problem

Asana Link: https://app.asana.com/0/1125705697210963/1136495241324181

## Testing Done and Results

Passed.

## Follow-up Work Needed

Change supervisor config to adapt the change of removing supervisor flag.

### CODE REVIEW

**Comment by cuonglm** [comment]
> Just an thought
> 
> Shall we check available validators before creating blocks, as block creation number of connected validators

Would you mind explaining more details, or pointing out to the code which does that.

**Comment by niktrix** [comment]
https://github.com/herdius/herdius-core/blob/master/supervisor/service/service.go#L816

If the validator is removed before that, it will never reach its vote count

**Comment by cuonglm** [comment]
> https://github.com/herdius/herdius-core/blob/master/supervisor/service/service.go#L816
> 
> If the validator is removed before that, it will never reach its vote count

But the voteCount won't be increased in the same situation, because the voteCount depends on number of validator groups, which depends on number of validators.

**Comment by niktrix** [comment]
In rare case, if the validator has given a vote and disconnected just after that,

**Comment by cuonglm** [comment]
> In rare case, if the validator has given a vote and disconnected just after that,

Ah right, so we can't do it either before or after this PR.

Please create other issue to track that problem.

**Pull request merged**
